import "./index.css";
import { Composition } from "remotion";
import {
  ENTRY_DURATION_IN_FRAMES,
  EXPORT_DURATION_IN_FRAMES,
  FILTER_DURATION_IN_FRAMES,
  GUIDE_DURATION_IN_FRAMES,
  FULL_DURATION_IN_FRAMES,
  BROWSE_DURATION_IN_FRAMES,
  PRODUCT_DURATION_IN_FRAMES,
  DETAIL_DURATION_IN_FRAMES,
  PROFILE_CHAPTER_DURATION_IN_FRAMES,
  PROFILE_ENTRY_DURATION_IN_FRAMES,
  FILES_DURATION_IN_FRAMES,
  THANKS_DURATION_IN_FRAMES,
  GOALS_DURATION_IN_FRAMES,
  INTRO_DURATION_IN_FRAMES,
  PROMPT_DURATION_IN_FRAMES,
  OVERVIEW_DURATION_IN_FRAMES,
  SIYU_LIXUAN_POSTER_DURATION_IN_FRAMES,
  SiyuLixuanPosterComposition,
  TrainingFullComposition,
  TrainingBrowseComposition,
  TrainingProductComposition,
  TrainingDetailComposition,
  TrainingProfileChapterComposition,
  TrainingProfileEntryComposition,
  TrainingFilesComposition,
  TrainingThanksComposition,
  TrainingEntryComposition,
  TrainingExportComposition,
  TrainingFilterComposition,
  TrainingGuideComposition,
  TrainingGoalsComposition,
  TrainingIntroComposition,
  TrainingOverviewComposition,
  TrainingPromptComposition,
} from "./Composition";

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="SiyuLixuanPoster"
        component={SiyuLixuanPosterComposition}
        durationInFrames={SIYU_LIXUAN_POSTER_DURATION_IN_FRAMES}
        fps={30}
        width={1440}
        height={2048}
      />
      <Composition
        id="WensliTrainingIntro"
        component={TrainingIntroComposition}
        durationInFrames={INTRO_DURATION_IN_FRAMES}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="WensliTrainingGoals"
        component={TrainingGoalsComposition}
        durationInFrames={GOALS_DURATION_IN_FRAMES}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="WensliTrainingOverview"
        component={TrainingOverviewComposition}
        durationInFrames={OVERVIEW_DURATION_IN_FRAMES}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="WensliTrainingGuide"
        component={TrainingGuideComposition}
        durationInFrames={GUIDE_DURATION_IN_FRAMES}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="WensliTrainingEntry"
        component={TrainingEntryComposition}
        durationInFrames={ENTRY_DURATION_IN_FRAMES}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="WensliTrainingPrompt"
        component={TrainingPromptComposition}
        durationInFrames={PROMPT_DURATION_IN_FRAMES}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="WensliTrainingFilter"
        component={TrainingFilterComposition}
        durationInFrames={FILTER_DURATION_IN_FRAMES}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="WensliTrainingExport"
        component={TrainingExportComposition}
        durationInFrames={EXPORT_DURATION_IN_FRAMES}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="WensliTrainingBrowse"
        component={TrainingBrowseComposition}
        durationInFrames={BROWSE_DURATION_IN_FRAMES}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="WensliTrainingProduct"
        component={TrainingProductComposition}
        durationInFrames={PRODUCT_DURATION_IN_FRAMES}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="WensliTrainingDetail"
        component={TrainingDetailComposition}
        durationInFrames={DETAIL_DURATION_IN_FRAMES}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="WensliTrainingProfileChapter"
        component={TrainingProfileChapterComposition}
        durationInFrames={PROFILE_CHAPTER_DURATION_IN_FRAMES}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="WensliTrainingProfileEntry"
        component={TrainingProfileEntryComposition}
        durationInFrames={PROFILE_ENTRY_DURATION_IN_FRAMES}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="WensliTrainingFiles"
        component={TrainingFilesComposition}
        durationInFrames={FILES_DURATION_IN_FRAMES}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="WensliTrainingThanks"
        component={TrainingThanksComposition}
        durationInFrames={THANKS_DURATION_IN_FRAMES}
        fps={30}
        width={1920}
        height={1080}
      />
      <Composition
        id="WensliTrainingFull"
        component={TrainingFullComposition}
        durationInFrames={FULL_DURATION_IN_FRAMES}
        fps={30}
        width={1920}
        height={1080}
      />
    </>
  );
};
